---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rrrrr/0/aa7.site/github3/
    - /usr/bin/git pull origin main
    - /usr/bin/git add -A
    - /usr/bin/git commit -m "Auto commit from cPanel"
    - /usr/bin/git push origin main
