deployment:
  tasks:
    - export DEPLOYPATH1=/home/seo88/public_html/gg
    - /bin/cp -R aset/img/lucky $DEPLOYPATH1
    
    - export DEPLOYPATH_CPANEL=/home/rrrrr/0/aa7.site/gg 
    - /bin/cp -R aset $DEPLOYPATH_CPANEL
