===

deployment:
  tasks:
    - export DEPLOYPATH=/home/rrrrr/0/aa7.site/gg
    - /usr/local/cpanel/3rdparty/bin/git pull origin main
    - /usr/local/cpanel/3rdparty/bin/git add --all
    - /usr/local/cpanel/3rdparty/bin/git commit -m "Auto-commit"
    - /usr/local/cpanel/3rdparty/bin/git push origin main
