##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rrrrr/0/aa7.site/g1/
    - /bin/cp -R img $DEPLOYPATH
    /bin/cp index.html $DEPLOYPATH
